#!/usr/bin/env python3
"""RAG-only native macOS installation and service management. STT stays independent."""

import argparse
import fcntl
import tempfile
import json
import os
import plistlib
import secrets
import shutil
import socket
import subprocess
import sys
import tarfile
import time
from pathlib import Path

from support.deployment import replace_code_tree

ROOT = Path(__file__).resolve().parents[1]
DEPLOY = Path.home() / "Library/Application Support/MeetingbotRAG"
LABEL = "com.meetingbot.rag"
PLIST = Path.home() / "Library/LaunchAgents" / f"{LABEL}.plist"
TARGET = f"gui/{os.getuid()}/{LABEL}"
TAILSCALE = "/Applications/Tailscale.app/Contents/MacOS/Tailscale"
LOGS = Path.home() / "Library/Logs/MeetingbotRAG"


def run(args, **kwargs):
    return subprocess.run([str(x) for x in args], check=True, **kwargs)


def loaded():
    return (
        subprocess.run(["launchctl", "print", TARGET], capture_output=True).returncode
        == 0
    )


def verify_owner():
    if PLIST.exists():
        p = plistlib.loads(PLIST.read_bytes())
        if p.get("Label") != LABEL or p.get("ProgramArguments", [""])[0] != str(
            DEPLOY / "rag/.venv/bin/python"
        ):
            raise SystemExit("Unexpected LaunchAgent owner; no changes made.")


def config(env=ROOT / ".env.rag"):
    # dotenv values generated by this CLI are JSON strings or booleans, with no shell evaluation.
    values = {}
    if env.exists():
        for line in env.read_text().splitlines():
            if line.strip() and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                try:
                    values[k] = json.loads(v)
                except (ValueError, TypeError):
                    values[k] = v.strip("\"'")
    return values


def write_config(path, values):
    path.write_text(
        "\n".join(
            k + "=" + json.dumps(v, ensure_ascii=False) for k, v in values.items()
        )
        + "\n"
    )
    path.chmod(0o600)


def state_dir():
    p = Path(config().get("RAG_DATA_DIR", ROOT / ".rag-data")).expanduser()
    return p if p.is_absolute() else ROOT / p


def init():
    if sys.platform != "darwin":
        raise SystemExit("This installation script has only been tested on macOS.")
    data = state_dir()
    data.mkdir(parents=True, exist_ok=True, mode=0o700)
    data.chmod(0o700)
    values = config()
    token = Path(values.get("RAG_AUTH_TOKEN_FILE", data / "admin-token"))
    if not token.exists():
        token.write_text(secrets.token_urlsafe(32))
        token.chmod(0o600)
    docs = Path.home() / "MeetingDocs"
    docs.mkdir(exist_ok=True)
    roots = ROOT / "config/source-roots.yaml"
    if not roots.exists():
        roots.parent.mkdir(exist_ok=True)
        roots.write_text(
            json.dumps(
                {
                    "roots": [
                        {"id": "meeting-docs", "label": "회의 자료", "path": str(docs)}
                    ]
                },
                ensure_ascii=False,
                indent=2,
            )
        )
    values.setdefault("RAG_DATA_DIR", str(data))
    values.setdefault("RAG_SOURCE_ROOTS_FILE", str(roots))
    values.setdefault("RAG_AUTH_TOKEN_FILE", str(token))
    write_config(ROOT / ".env.rag", values)
    print("Initialized. Configure source roots locally:", roots)


def install_deps():
    uv = shutil.which("uv") or "/opt/homebrew/bin/uv"
    npm = shutil.which("npm")
    if not Path(uv).exists() or not npm:
        raise SystemExit("Install uv and Node.js/npm first.")
    run([uv, "sync", "--project", ROOT / "rag", "--frozen"])
    run([npm, "ci", "--prefix", ROOT / "frontend", "--cache", DEPLOY / "npm-cache"])
    run([npm, "--prefix", ROOT / "frontend", "run", "build"])


def stop():
    verify_owner()
    if loaded():
        run(["launchctl", "bootout", TARGET])
        for _ in range(60):
            with socket.socket() as sock:
                if sock.connect_ex(("127.0.0.1", 8766)) != 0 and not loaded():
                    break
            time.sleep(0.5)
        else:
            raise SystemExit(
                "Port 8766 remains in use; do not replace a running data owner."
            )


def backup():
    if loaded():
        raise SystemExit("Stop RAG before backup; STT can remain running.")
    data = state_dir()
    dest = DEPLOY / "backups"
    dest.mkdir(parents=True, exist_ok=True, mode=0o700)
    target = dest / (time.strftime("%Y%m%d-%H%M%S") + "-" + secrets.token_hex(3) + ".tar.gz")
    with (
        (data / "service.lock").open("a+") as guard,
        tarfile.open(target, "w:gz") as archive,
    ):
        try:
            fcntl.flock(guard, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            raise SystemExit(
                "Another RAG process owns the data; stop it before backup."
            ) from None
        for p in data.iterdir():
            if p.name not in {"models", "service.lock", "admin-token"}:
                archive.add(p, arcname="data/" + p.name)
    target.chmod(0o600)
    print("Backup (model cache/admin token excluded; private settings included):", target)
    return target


def restore(archive_path):
    if loaded():
        raise SystemExit(
            "Stop RAG first, then choose an empty RAG_DATA_DIR for restore."
        )
    data = state_dir()
    if (data / "registry.sqlite").exists() or (data / "workspaces").exists():
        raise SystemExit(
            "Restore requires an empty data directory; existing data was preserved."
        )
    data.mkdir(parents=True, exist_ok=True, mode=0o700)
    with tempfile.TemporaryDirectory(dir=data.parent, prefix="rag-restore-") as temp:
        temp = Path(temp)
        with tarfile.open(archive_path, "r:gz") as archive:
            for member in archive.getmembers():
                parts = Path(member.name).parts
                if (
                    not parts
                    or parts[0] != "data"
                    or ".." in parts
                    or Path(member.name).is_absolute()
                    or not (member.isfile() or member.isdir())
                ):
                    raise SystemExit(
                        "Unsafe backup archive; no live data was replaced."
                    )
            for member in archive.getmembers():
                destination = temp.joinpath(*Path(member.name).parts)
                if member.isdir():
                    destination.mkdir(parents=True, exist_ok=True, mode=0o700)
                else:
                    destination.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
                    with (
                        archive.extractfile(member) as source,
                        destination.open("xb") as target,
                    ):
                        shutil.copyfileobj(source, target)
                    destination.chmod(0o600)
        restored = temp / "data"
        if not (restored / "registry.sqlite").is_file():
            raise SystemExit("Backup has no registry database.")
        for item in restored.iterdir():
            if (data / item.name).exists():
                raise SystemExit(
                    "Destination contains conflicting files; no overwrite allowed."
                )
        for item in restored.iterdir():
            shutil.move(str(item), str(data / item.name))
    print(
        "Restored to",
        data,
        ". Keep source-root IDs and paths unchanged, prepare model cache, then start.",
    )


def deploy():
    verify_owner()
    if (
        not (ROOT / "rag/.venv/bin/python").exists()
        or not (ROOT / "frontend/dist/index.html").exists()
    ):
        raise SystemExit(
            "Run install first to prepare the Python environment and web build."
        )
    stop()
    if (state_dir() / "registry.sqlite").exists():
        backup()
    DEPLOY.mkdir(parents=True, exist_ok=True, mode=0o700)
    DEPLOY.chmod(0o700)
    replace_code_tree(ROOT / "rag/meetingbot_rag", DEPLOY / "rag/meetingbot_rag")
    shutil.copytree(ROOT / "shared", DEPLOY / "shared", dirs_exist_ok=True)
    for folder in ("frontend/dist", "prompts", "config"):
        shutil.copytree(
            ROOT / folder,
            DEPLOY / folder,
            dirs_exist_ok=True,
            ignore=shutil.ignore_patterns("__pycache__"),
        )
    for name in ("pyproject.toml", "uv.lock"):
        shutil.copy2(ROOT / "rag" / name, DEPLOY / "rag" / name)
    uv = shutil.which("uv") or "/opt/homebrew/bin/uv"
    run([uv, "sync", "--project", DEPLOY / "rag", "--frozen", "--no-dev"])
    values = config()
    values["RAG_DATA_DIR"] = str(state_dir())
    auth = Path(
        values.get("RAG_AUTH_TOKEN_FILE", state_dir() / "admin-token")
    ).expanduser()
    values["RAG_AUTH_TOKEN_FILE"] = str(auth if auth.is_absolute() else ROOT / auth)
    # launchd cannot reliably read Documents due to macOS privacy restrictions.
    roots = Path(values["RAG_SOURCE_ROOTS_FILE"]).expanduser()
    if not roots.is_absolute():
        roots = ROOT / roots
    shutil.copy2(roots, DEPLOY / "config/source-roots.yaml")
    values["RAG_SOURCE_ROOTS_FILE"] = str(DEPLOY / "config/source-roots.yaml")
    write_config(DEPLOY / ".env.rag", values)
    PLIST.parent.mkdir(parents=True, exist_ok=True)
    LOGS.mkdir(parents=True, exist_ok=True, mode=0o700)
    definition = {
        "Label": LABEL,
        "ProgramArguments": [
            str(DEPLOY / "rag/.venv/bin/python"),
            "-m",
            "uvicorn",
            "meetingbot_rag.app:create_app",
            "--factory",
            "--host",
            "127.0.0.1",
            "--port",
            "8766",
            "--workers",
            "1",
            "--no-access-log",
            "--proxy-headers",
            "--forwarded-allow-ips",
            "127.0.0.1",
        ],
        "WorkingDirectory": str(DEPLOY / "rag"),
        "RunAtLoad": True,
        "KeepAlive": True,
        "ThrottleInterval": 5,
        "Umask": 63,
        "EnvironmentVariables": {
            "PATH": "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
            "PYTHONUNBUFFERED": "1",
            "TOKENIZERS_PARALLELISM": "false",
            "HF_HUB_DISABLE_TELEMETRY": "1",
            "LANGSMITH_TRACING": "false",
            "LANGCHAIN_TRACING_V2": "false",
        },
        "StandardOutPath": str(LOGS / "stdout.log"),
        "StandardErrorPath": str(LOGS / "stderr.log"),
    }
    PLIST.write_bytes(plistlib.dumps(definition))
    PLIST.chmod(0o600)
    for attempt in range(30):
        p = subprocess.run(
            ["launchctl", "bootstrap", f"gui/{os.getuid()}", str(PLIST)],
            capture_output=True,
            text=True,
        )
        if p.returncode == 0:
            break
        if p.returncode != 5 or attempt == 29:
            raise SystemExit(p.stderr)
        time.sleep(0.5)
    print("RAG service installed. STT service was not changed. Logs:", LOGS)


def tailscale():
    status = json.loads(
        run([TAILSCALE, "status", "--json"], capture_output=True, text=True).stdout
    )
    if status["BackendState"] != "Running":
        raise SystemExit("Connect Tailscale first.")
    host = status["Self"]["DNSName"].rstrip(".")
    ip = next(x for x in status["TailscaleIPs"] if ":" not in x)
    # Never reset Serve or change existing STT routes.
    current = json.loads(
        run(
            [TAILSCALE, "serve", "status", "--json"], capture_output=True, text=True
        ).stdout
        or "{}"
    )
    for port in ("8443", "8766"):
        existing = current.get("TCP", {}).get(port)
        if existing:
            if port == "8766" and existing.get("TCPForward") != "127.0.0.1:8766":
                raise SystemExit(
                    "Port 8766 is already owned by another Tailscale service."
                )
            if port == "8443":
                handler = (
                    current.get("Web", {})
                    .get(host + ":8443", {})
                    .get("Handlers", {})
                    .get("/", {})
                )
                if handler.get("Proxy") != "http://127.0.0.1:8766":
                    raise SystemExit(
                        "HTTPS port 8443 is already owned by another Tailscale service."
                    )
    values = config()
    origin = "https://" + host + ":8443"
    values.update(
        RAG_ACCESS_MODE="remote",
        RAG_PUBLIC_ORIGIN=origin,
        RAG_ALLOWED_HOSTS=["127.0.0.1", "localhost", host, ip],
        RAG_ORIGINS=[origin, "http://127.0.0.1:8766", "http://localhost:8766"],
        RAG_REDIRECT_HOSTS=[ip],
    )
    write_config(ROOT / ".env.rag", values)
    deploy()
    run([TAILSCALE, "serve", "--bg", "--https=8443", "http://127.0.0.1:8766"])
    run([TAILSCALE, "serve", "--bg", "--tcp=8766", "tcp://127.0.0.1:8766"])
    print("IP entry: http://" + ip + ":8766/rag")
    print("HTTPS: " + origin + "/rag")


def access_link():
    values = config()
    token = (
        Path(values.get("RAG_AUTH_TOKEN_FILE", state_dir() / "admin-token"))
        .read_text()
        .strip()
    )
    print(
        values.get("RAG_PUBLIC_ORIGIN", "http://127.0.0.1:8766") + "/rag#token=" + token
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "action",
        choices=[
            "init",
            "install",
            "start",
            "restart",
            "stop",
            "status",
            "access-link",
            "download-model",
            "tailscale",
            "backup",
            "restore",
            "uninstall",
        ],
    )
    parser.add_argument(
        "--archive", type=Path, help="Trusted backup archive for restore"
    )
    args = parser.parse_args()
    if args.action == "init":
        init()
    elif args.action == "install":
        init()
        install_deps()
        deploy()
    elif args.action in ("start", "restart"):
        deploy()
    elif args.action == "stop":
        stop()
    elif args.action == "status":
        run(["launchctl", "print", TARGET])
    elif args.action == "access-link":
        access_link()
    elif args.action == "download-model":
        sys.path.insert(0, str(ROOT / "rag"))
        from meetingbot_rag.adapters import LocalEmbedding
        from meetingbot_rag.settings import Settings

        s = Settings()
        s.prepare()
        m = LocalEmbedding(s)
        m.load(download=True)
        print(m.health())
    elif args.action == "tailscale":
        tailscale()
    elif args.action == "backup":
        backup()
    elif args.action == "restore":
        if not args.archive:
            parser.error("restore requires --archive")
        restore(args.archive)
    elif args.action == "uninstall":
        stop()
        PLIST.unlink(missing_ok=True)
        print(
            "RAG LaunchAgent removed. Application, credentials, user data, original documents and STT are preserved."
        )
