import {chromium} from '../frontend/node_modules/playwright-core/index.mjs';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const config=Object.fromEntries((await readFile(path.join(root,'.env.rag'),'utf8')).trim().split('\n').filter(x=>x&&!x.startsWith('#')).map(line=>{const i=line.indexOf('=');let v=line.slice(i+1);try{v=JSON.parse(v)}catch{}return [line.slice(0,i),v]}));
const base=config.RAG_PUBLIC_ORIGIN;
const key=(await readFile(config.RAG_AUTH_TOKEN_FILE,'utf8')).trim();
const output=path.join(config.RAG_DATA_DIR,'ui-qa');await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const report={checks:[],errors:[],requests:[]};
let createdId=null;
try{
 const context=await browser.newContext({viewport:{width:1440,height:1060}});
 const page=await context.newPage();
 page.on('pageerror',e=>report.errors.push(e.message));
 page.on('request',request=>{if(request.url().includes('/api/'))report.requests.push({method:request.method(),url:request.url()});});
 await page.goto(base+'/rag');
 await page.getByLabel('워크스페이스 접속 키',{exact:true}).fill(key);
 await page.getByRole('button',{name:'라이브러리 열기',exact:true}).click();
 await page.getByRole('button',{name:'워크스페이스 만들기',exact:true}).waitFor();
 report.checks.push('HTTPS browser login and workspace library');
 await page.screenshot({path:path.join(output,'library-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'워크스페이스 만들기',exact:true}).click();
 await page.getByText('워크스페이스에 연결된 공유 폴더',{exact:true}).waitFor();
 await page.getByRole('button',{name:'sample-project-a',exact:true}).click();
 await page.getByRole('button',{name:'이 폴더 사용',exact:true}).click();
 await page.getByLabel('이름',{exact:true}).fill('E2E 검증용 워크스페이스');
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('button')).find(b=>b.textContent.includes('만들고 자료 준비 시작'))?.disabled===false);
 report.checks.push('server folder browse, explicit folder selection and persistent preview');
 await page.screenshot({path:path.join(output,'folder-preview.png'),fullPage:true});
 const indexStarted=page.waitForResponse(r=>r.url().endsWith('/index-jobs')&&r.request().method()==='POST');
 const created=page.waitForResponse(r=>r.url()===base+'/api/rag/workspaces'&&r.request().method()==='POST');
 await page.getByRole('button',{name:'만들고 자료 준비 시작',exact:true}).click();
 createdId=(await (await created).json()).id;
 assert.equal((await indexStarted).status(),202);
 // Close tab while indexing; re-open with the same session and recover job state.
 await page.close();
 const next=await context.newPage();next.on('pageerror',e=>report.errors.push(e.message));
 await next.goto(base+'/rag');
 await next.locator('.rag-spaces button').filter({hasText:'E2E 검증용 워크스페이스'}).click();
 await next.getByLabel('검색 질문',{exact:true}).fill('로그 보관 기간은 얼마인가요?');
 await next.waitForFunction(()=>Array.from(document.querySelectorAll('button')).find(b=>b.textContent.trim()==='근거 검색')?.disabled===false,{},{timeout:90000});
 report.checks.push('close browser tab during indexing; reconnect and recover persisted READY job');
 await next.getByLabel('검색 질문',{exact:true}).fill('로그 보관 기간은 얼마인가요?');
 await next.getByRole('button',{name:'근거 검색',exact:true}).click();
 await next.locator('.rag-evidence-card').filter({hasText:'90일'}).first().waitFor();
 await next.locator('.rag-evidence-card').filter({hasText:'90일'}).first().getByRole('button',{name:'원문 보기'}).click();
 await next.locator('.rag-source-lines .highlight').filter({hasText:'90일'}).waitFor();
 report.checks.push('real Korean search and original line snapshot in browser');
 await next.screenshot({path:path.join(output,'source-desktop.png'),fullPage:true});
 await next.getByRole('button',{name:'원문 닫기'}).click();
 await next.locator('.rag-spaces button').filter({hasText:'샘플 프로젝트 B'}).click();
 assert.equal(await next.locator('.rag-evidence-card').count(),0);
 assert.equal(await next.getByLabel('검색 질문',{exact:true}).inputValue(),'');
 await next.getByLabel('검색 질문',{exact:true}).fill('로그 보관 기간');
 await next.getByRole('button',{name:'근거 검색',exact:true}).click();
 await next.locator('.rag-evidence-card').filter({hasText:'30일'}).first().waitFor();
 assert.equal(await next.locator('.rag-evidence-card').filter({hasText:'90일'}).count(),0);
 report.checks.push('workspace switch clears prior search and isolates 30-day policy');
 await next.screenshot({path:path.join(output,'search-desktop.png'),fullPage:true});
 await next.setViewportSize({width:390,height:844});
 await next.screenshot({path:path.join(output,'search-mobile.png'),fullPage:true});
 const overflow=await next.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
 assert.equal(overflow,false,'mobile horizontal overflow');
 report.checks.push('390px mobile layout has no horizontal overflow');
 // Requests from the browser must use the public origin only, with no internal ports.
 assert(report.requests.every(r=>r.url.startsWith(base+'/api/rag/')));
 report.checks.push('browser API requests stay on the same public HTTPS origin');
 // Real delayed response across workspaces, not just the scope helper unit test.
 await next.setViewportSize({width:1440,height:1060});
 await next.locator('.rag-spaces button').filter({hasText:'샘플 프로젝트 A'}).click();
 await next.route('**/api/rag/workspaces/*/search',async route=>{const response=await route.fetch();await new Promise(r=>setTimeout(r,1200));await route.fulfill({response}).catch(()=>{});},{times:1});
 await next.getByLabel('검색 질문',{exact:true}).fill('로그 보관 기간');
 const pending=next.waitForRequest(r=>r.url().endsWith('/search'));
 await next.getByRole('button',{name:'근거 검색',exact:true}).click();await pending;
 await next.locator('.rag-spaces button').filter({hasText:'샘플 프로젝트 B'}).click();
 await next.waitForTimeout(1500);
 assert.equal(await next.locator('.rag-evidence-card').count(),0);
 report.checks.push('late A search response is discarded after switching to B');
 assert.deepEqual(report.errors,[]);
 await context.close();
}finally{
 if(createdId){const response=await fetch(base+'/api/rag/workspaces/'+createdId,{method:'DELETE',headers:{Authorization:'Bearer '+key}});assert.equal(response.status,200);report.checks.push('delete synthetic E2E workspace; originals preserved');}
 await browser.close();
 await writeFile(path.join(root,'docs/rag/ui-test-results.json'),JSON.stringify(report,null,2));
}
console.log(JSON.stringify({checks:report.checks,errors:report.errors,screenshots:output},null,2));
